### PR TITLE
a little refactoring

### PR DESCRIPTION
**Pull request by guybedford**
Ok.. Been working on cleaning the code up a little.

### CODE REVIEW

**Comment by guybedford** [comment]
Some points:
- `context.db_server` to store the database URL
- `context.home` to store the homepage path
- Combine server and client handlers into one. They can even be inlined soon with that work!
- Use spread operator and simplify views.

The idea is that this package shares _components_ and _views_ (our route components).

The two views are Article and ArticleList. Which in turn have their own handlers. In turn these handlers only need to assume basic context info.

**Comment by guybedford** [comment]
A key question I've been asking myself - why is `loadRoute` used everywhere and not `curRoute`?

**Comment by guybedford** [comment]
Also it's important to use ES6 everywhere and no CommonJS.

**Comment by Bubblyworld** [comment]
loadRoute refers to the request currently being executed and rendered. curRoute refers to the request that is _already_ rendered. This is never present on the server as we do not do any form of persistence, so we refer to loadRoute all the time.

**Comment by guybedford** [comment]
Thanks - is there a reason this can't just be `curRoute` or even just `route` throughout? In terms of thinking about it - on the server we consider the page to sit at the "rendered" state immediately. It's only on the client that `loadRoute` / `loadingRoute` applies. This way the state persists cleanly too between.

**Comment by Bubblyworld** [comment]
I suppose I felt consistency writing code on the client and server would be nice. Do you mean making the distinction on the client, but on the server just having curRoute throughout sort of thing?

**Comment by guybedford** [comment]
Ok sorry, I see what you mean - `loadRoute` is the one that has to trigger the handler because on the client it's not rendered yet. Ok, my sincere apologies that is fine then. But in terms of writing code, we should only refer to `loadRoute` in handlers, and `curRoute` in render functions always.

**Comment by Bubblyworld** [comment]
A good point. I'll work that in.

**Comment by guybedford** [comment]
To clarify something else - handlers are run in parallel for the tree? Or are they run sequentially down the tree?

**Comment by Bubblyworld** [comment]
Sequentially down the tree

**Comment by Bubblyworld** [comment]
In order from least general route match to most specific. We need this, for instance, to allow auth checks in a base handler that redirect on failure.

**Pull request merged**
